/**
 * ⚠️ DO NOT EDIT
 * -------------
 * This file was autogenerated by Proser.
 * Edits may be overwritten.
 */
import React from 'react'

export const postsMap = {
  'introducing-proser': {
    id: 0,
    slug: 'introducing-proser',

    component: /*#__PURE__*/ React.lazy(() =>
      import('./0-introducing-proser.mdx')
    ),
    metadata: {
      title: '✐ Introducing Proser',
      description: "This blog you're looking at? This is Proser.",
      get image() {
        return import('@assets/bali.720.jpg')
      },
      timestamp: 1597628866203,
      tags: ['proser', 'node', 'react'],
      categories: ['oss', 'weekend builds'],
    },
  },
}

export const posts = Object.values(postsMap)
export const postsMapById = posts.reduce((acc, post) => {
  acc[post.id] = post
  return acc
}, {})
