/**
 * ⚠️ DO NOT EDIT
 * -------------
 * This file was autogenerated by Proser.
 * Edits may be overwritten.
 */
import React from 'react'
/*__PROSER_HOISTED_STRINGS__*/ const _proserRef0 = 'Proser',
  _proserRef1 = 'Node',
  _proserRef2 = 'React',
  _proserRef3 = '1 min read'

const {lazy} = React

export const postsMap = {
  'introducing-proser': {
    id: 0,
    slug: 'introducing-proser',

    component: lazy(() => import('./0-introducing-proser.mdx')),
    metadata: {
      title: '✐ Introducing Proser',
      description: "This blog you're looking at? This is Proser.",
      get image() {
        return import('@assets/bali.720.jpg')
      },
      timestamp: 1597628866203,
      tags: ['Proser', 'Node', 'React'],
      categories: ['OSS', 'Weekend Builds'],
      readingTime: {text: '3 min read', time: 127200, words: 424},
    },
  },
}

export const posts = Object.values(postsMap)
export const postsMapById = posts.reduce((acc, post) => {
  acc[post.id] = post
  return acc
}, {})
