/**
 * ⚠️ DO NOT EDIT
 * -------------
 * This file was autogenerated by Proser.
 * Edits may be overwritten.
 */
import React from 'react'

export const postsMap = {
  'introducing-proser': {
    id: 0,
    slug: 'introducing-proser',

    component: /*#__PURE__*/ React.lazy(() =>
      import('./0-introducing-proser.mdx')
    ),
    metadata: {
      title: '✐ Introducing Proser',
      description: "This blog you're looking at? This is Proser.",
      get image() {
        return import('@assets/bali.720.jpg')
      },
      timestamp: 1597628866203,
      tags: ['Proser', 'Node', 'React'],
      categories: ['OSS', 'Weekend Builds'],
      readingTime: {text: '3 min read', time: 126300, words: 421},
    },
  },

  'setting-up-storybook-and-snowpack': {
    id: 1,
    slug: 'setting-up-storybook-and-snowpack',

    component: /*#__PURE__*/ React.lazy(() =>
      import('./1-setting-up-storybook-and-snowpack.mdx')
    ),
    metadata: {
      title: 'Setting up Storybook in a Snowpack project',
      description: /*#__PURE__*/ React.createElement(
        React.Fragment,
        null,
        'In this post I cover how to make Storybook play nicely with Snowpack semantics like ',
        /*#__PURE__*/ React.createElement('code', null, 'import.meta.env'),
        ' instead of',
        ' ',
        /*#__PURE__*/ React.createElement('code', null, 'process.env')
      ),
      timestamp: 1597879288280,
      tags: ['Storybook', 'Snowpack'],
      categories: ['Frontend'],
      readingTime: {text: '1 min read', time: 13800, words: 46},
    },
  },

  'write-fewer-components': {
    id: 2,
    slug: 'write-fewer-components',

    component: /*#__PURE__*/ React.lazy(() =>
      import('./2-write-fewer-components.mdx')
    ),
    metadata: {
      title: 'Write fewer components',
      description:
        'In which I offer an alternative to abstractions like styled-components, styled-system, and others that promote writing unique styles for every element.',
      timestamp: 1597896907299,
      tags: ['React', 'CSS', 'JavaScript'],
      categories: ['Opinion', 'Frontend'],
      readingTime: {text: '1 min read', time: 12300, words: 41},
    },
  },
  'in-defense-of-rolling-your-own': {
    id: 3,
    slug: 'in-defense-of-rolling-your-own',
    component: /*#__PURE__*/ React.lazy(() =>
      import('./3-in-defense-of-rolling-your-own.mdx')
    ),
    metadata: {
      title: 'In defense of rolling your own ____',
      description:
        'Developers love to tell you not to reinvent the wheel. But what if you really, really want to?',
      timestamp: 1597962733761,
      tags: [],
      categories: ['Opinion', 'Motivation'],
      readingTime: {text: '1 min read', time: 13500, words: 45},
    },
  },
}

export const posts = Object.values(postsMap)
export const postsMapById = posts.reduce((acc, post) => {
  acc[post.id] = post
  return acc
}, {})
