/**
 * ⚠️ DO NOT EDIT
 * -------------
 * This file was autogenerated by Proser.
 * Edits may be overwritten.
 */
import dynamic from "next/dynamic";
import React from "react";
/*__PROSER_HOISTED_STRINGS__*/ const _macro2 = "macro",
  _HowTo2 = "How-to",
  _Snowpack2 = "Snowpack",
  _Webpack2 = "Webpack",
  _Frontend2 = "Frontend",
  _minRead2 = "2 min read";

export const postsMap = {
  "write-your-first-babel-plugin": {
    id: 0,
    slug: "write-your-first-babel-plugin",

    component: dynamic(() => import("./0-write-your-first-babel-plugin.mdx")),
    metadata: {
      title: "So you want to write a Babel plugin",
      description:
        "Here are the Babel plugin basics and resources you need to get started.",
      timestamp: 1598459311282,
      type: _macro2,
      tags: ["Babel", "Node"],
      categories: [_HowTo2],
      readingTime: { text: "5 min read", time: 284400, words: 948 },
    },
  },

  "drop-your-bundler-in-2020": {
    id: 1,
    slug: "drop-your-bundler-in-2020",

    component: dynamic(() => import("./1-drop-your-bundler-in-2020.mdx")),
    metadata: {
      title: "Drop your bundler in 2020",
      description:
        "Snowpack and ES modules are the future of the web. If you don't need to support legacy browsers, why not drop your bundler?",
      timestamp: 1598476509136,
      type: _macro2,
      tags: [_Snowpack2, _Webpack2, "Rollup", "Parcel", "ES modules"],
      categories: ["Hot takes", _Frontend2],
      readingTime: { text: _minRead2, time: 104400, words: 348 },
    },
  },

  "set-up-storybook-in-a-snowpack-project": {
    id: 2,
    slug: "set-up-storybook-in-a-snowpack-project",

    component: dynamic(() =>
      import("./2-set-up-storybook-in-a-snowpack-project.mdx")
    ),
    metadata: {
      title: "Set up Storybook in a Snowpack project ",
      description:
        "How to fix common issues when adding Storybook to a Snowpack app.",
      timestamp: 1598485593466,
      type: _macro2,
      tags: [_Snowpack2, _Webpack2, "Storybook"],
      categories: [_HowTo2, _Frontend2],
      readingTime: { text: _minRead2, time: 78300, words: 261 },
    },
  },

  "on-death-and-dying": {
    id: 3,
    slug: "on-death-and-dying",

    component: dynamic(() => import("./3-on-death-and-dying.mdx")),
    metadata: {
      title: "On death and dying",
      description:
        "A timeline of my relationship with death, its inevitability, and my futile resistance.",
      timestamp: 1598572358549,
      get image() {
        return "/sleep-paralysis.jpg";
      },
      type: _macro2,
      tags: ["Mortality", "Personal"],
      categories: ["Philosophy"],
      readingTime: { text: "8 min read", time: 434100, words: 1447 },
    },
  },
};

export const posts = Object.values(postsMap);
export const postsMapById = posts.reduce((acc, post) => {
  acc[post.id] = post;
  return acc;
}, {});
